[main]
font=JetBrainsMono Nerd Font:size=7
width=50
lines=10
line-height=26
horizontal-pad=24
vertical-pad=18
inner-pad=10
icon-theme=Papirus
dpi-aware=yes

[border]
width=2
radius=10

[colors]
background=1e1e2ecc
text=cdd6f4ff
match=f38ba8ff
selection=313244ff
selection-text=cdd6f4ff
selection-match=f38ba8ff
border=89b4faff


; [main]
; width=80
; lines=20
; horizontal-pad=20
; vertical-pad=20
