# -------------------------

# ZOXIDE DIRECTORY JUMP

# -------------------------

[[mgr.prepend_keymap]]
on = ["z"]
run = "plugin zoxide"
desc = "Jump to directory (zoxide)"

# -------------------------

# OPEN - bypass opener system (handles empty/new files too)

# -------------------------

[[mgr.prepend_keymap]]
on = ["<Enter>"]
run = ['shell --block -- [ ! -d "%h" ] && nvim "%h" || true', 'enter']
desc = "Edit file or enter directory"

# -------------------------

# OPEN WITH MENU

# -------------------------

[[mgr.prepend_keymap]]
on = ["o"]
run = "open --interactive"
desc = "Open with..."

# -------------------------

# REVEAL FILE IN GUI

# -------------------------

[[mgr.prepend_keymap]]
on = ["O"]
run = "reveal"
desc = "Reveal in system file manager"

# -------------------------

# COMMON LOCATIONS

# -------------------------

[[mgr.prepend_keymap]]
on = ["g","h"]
run = "cd ~"
desc = "Home"

[[mgr.prepend_keymap]]
on = ["g","."]
run = "cd ~/.config"
desc = "~/.config"

[[mgr.prepend_keymap]]
on = ["g","d"]
run = "cd ~/Downloads"
desc = "~/Downloads"

[[mgr.prepend_keymap]]
on = ["g","<Space>"]
run = "cd --interactive"
desc = "Jump interactively"

[[mgr.prepend_keymap]]
on = ["g","p"]
run = "cd ~/dotfiles/"
desc = "dotfiles"

[[mgr.prepend_keymap]]
on = ["g","m"]
run = "cd /mnt/"
desc = "mount drives"

# YOUR DEV SHORTCUTS

# -------------------------

[[mgr.prepend_keymap]]
on = ["g","k"]
run = "cd ~/dotfiles/niri/.config/niri/cfg/"
desc = "Niri keymap"

[[mgr.prepend_keymap]]
on = ["g","n"]
run = "cd ~/.config/nvim/lua/config/"
desc = "Neovim config"

# -------------------------

# QUICK SEARCH

# -------------------------


# -------------------------

# GLOBAL FILE SEARCH

# -------------------------

[[mgr.prepend_keymap]]
on = ["f"]
run = "plugin fd"
desc = "Find file (fd)"

# -------------------------

# COPY PATH

# -------------------------
#
# [[mgr.prepend_keymap]]
# on = ["y","p"]
# run = "yank path"
# desc = "Copy file path"
#
# # -------------------------
#
# # COPY FILE NAME
#
# # -------------------------
#
# [[mgr.prepend_keymap]]
# on = ["y","n"]
# run = "yank name"
# desc = "Copy file name"
